### ISSUE TITLE
Support different healthcheck verification interval during container start

### ISSUE THREAD

**Issue by paulo-raca** [docker/roadmap#458]
**Tell us about your request**
I'd like to specify a distinct interval to execute healthchecks during container startup. I suggest calling it `--start-interval`

**Which service(s) is this request for?**
I'm particularly interested in using it in `compose`

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

I use docker-compose to launch several container, and some of them need to wait for dependencies to be ready before starting. 

I use healthchecks to achieve that, and my `docker-compose.yaml` looks like this:

```
services:
    database:
        [...]
        healthcheck:
            [...]
    backend:
        [...]
        depends_on:
            database:
                condition: service_healthy
```

While starting my services I want the `database`'s healthcheck to be executed often (e.g., every 0.1s), so that the `backend` starts as quickly as possible. However, once it is up, there is no need to check it continuously, and I'd like to use a larger interval (Maybe 30s)

**Are you currently working around the issue?**
I currently have healthcheck running every 1s
