### ISSUE TITLE
Add "latest" tag to Docker extensions

### ISSUE THREAD

**Issue by nuno-andre** [docker/roadmap#554]
**Tell us about your request**
Please, add a "latest" tag to every Docker extension in Docker Hub.

**Which service(s) is this request for?**
Docker Desktop

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Some Docker's Docker Desktop extensions (e.g. _Disk Usage_ or _Logs Explorer_) have no a `latest` tag in Docker Hub, so to install the latest version from the console it is necessary to know it beforehand since a (e.g.) `docker extension install docker/logs-explorer-extension -f` will fail.

**Are you currently working around the issue?**
We're using Ansbile to install Docker Desktop, so we came up with this solution:

```yaml
- shell: 'docker extension install {{ item }}:{{ version }} -f'
  vars:
    json: "{{ lookup('url', 'https://hub.docker.com/v2/repositories/{{ item }}/tags') | from_json }}"
    version: '{{ json.results[0].name }}'
  loop:
    - docker/disk-usage-extension
    - docker/logs-explorer-extension
  become: false
```
