### ISSUE TITLE
Docker compose, use include with networks

### ISSUE THREAD

**Issue by Rami-Kassouf-FOO** [docker/roadmap#785]
**Tell us about your request**
I want to split the docker composes for clarity but have 1 main compose to group them up when building tests for consistency. So i am using include in conjunction with networks

**Which service(s) is this request for?**
docker compose

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
My service in the front/ folder can t seem to acces the back folder's gateway service

I am trying to split my docker compose into 2 compose files: for example:

#front/docker-compose.yaml

```
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "80:80"
    networks:
      - project_gateway

networks:
  project_gateway:
    external: true
```
#back/docker-compose.yaml

```
services:
  gateway_service:
    build:
      context: ./gatewayService
      dockerfile: Dockerfile
    container_name: gateway_service
    ports:
      - "8000:8000"
    networks:
      - project_backend
      - project_gateway

  service_1:
    build:
      context: ./service_1
      dockerfile: Dockerfile
    container_name: service_1
    ports:
      - "8001:8001"
    networks:
      - project_backend
networks:
  project_backend:
    external: true
  project_gateway:
    external: true
```
and outside: #./docker-compose.yaml

```
networks:
  backend:
    driver: bridge
  gateway:
    driver: bridge


include:
  - back/docker-compose.yaml
  - front/docker-compose.yaml
```

**Are you currently working around the issue?**
`docker-compose -f docker-compose.yaml -f back/docker-compose.yaml -f front/docker-compose.yaml up` Should be a working alternative

**Additional context**
[stackoverflow#79430123](https://stackoverflow.com/questions/79430019/docker-compose-using-multiple-networks-with-include/79430123#79430123)

**Comment by devznsh** [comment]
I see the issue with your network configuration. The problem is that there's a **name mismatch** between the networks defined in your main `docker-compose.yaml` and those referenced in your included compose files.

## The Problem

In your main `./docker-compose.yaml`, you're defining:
```yaml
networks:
  backend:     # ← This name
  gateway:     # ← This name
```

But in your included files, you're referencing:
```yaml
networks:
  project_backend:  # ← Different name
  project_gateway:  # ← Different name
```

## The Solution

You have a couple of options to fix this:

### Option 1: Update your main compose file (Recommended)
Change your main `./docker-compose.yaml` to match the network names used in your included files:

```yaml
networks:
  project_backend:
    driver: bridge
  project_gateway:
    driver: bridge

include:
  - back/docker-compose.yaml
  - front/docker-compose.yaml
```

### Option 2: Use network name mapping
Alternatively, you can use the `name` property to map the networks:

```yaml
networks:
  backend:
    driver: bridge
    name: project_backend
  gateway:
    driver: bridge
    name: project_gateway

include:
  - back/docker-compose.yaml
  - front/docker-compose.yaml
```

### Option 3: Remove external: true
Since you're defining the networks in your main compose file, you should also remove `external: true` from your included compose files, as these networks are now being created by the main compose file rather than being external.

## Additional Notes

- The `include` directive in Docker Compose is relatively new (v2.20+), so make sure you're using a recent version
- Consider using a consistent naming convention across all your compose files to avoid such issues

Try Option 1 first - it should resolve the connectivity issue between your front and back services! 🚀
