### ISSUE TITLE
Allow scheduled autobuilds

### ISSUE THREAD

**Issue by bounlu** [docker/roadmap#818]
**Tell us about your request**
Allow scheduled autobuilds just like Github Actions schedule -> cron jobs

**Which service(s) is this request for?**
Dockerhub Autobuild

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Sometimes it's desirable to rebuild the Docker image on regular intervals even if there is no change in the code, such as upgrading the tools in the Dockerfile to the latest available versions if they are not pinned

**Are you currently working around the issue?**
No, but I created a workaround by adding a workflow to Github Actions to trigger Dockerhub by sending POST request to the endpoint

**Additional context**

My current workaround:
```
name: Docker Hub Build Trigger

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  trigger-docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Send POST request to endpoint
        run: |
          curl -X POST https://hub.docker.com/api/build/v1/source/3d8b72f1-0271-4b4c-a323-c5e82e2b1908/trigger/cef78025-cc9f-43a2-b84b-b5757268d26b/call/
```
